org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
forge_version=52.1.0
forge_version_range=[52,)
loader_version_range=[52,)
mapping_channel=official
mapping_version=1.21.1

## Mod Properties
mod_id=mastcraftvoice
mod_name=MastCraft Voice
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.mastcraft
mod_authors=MastCraft
mod_description=Proximity voice chat over Minecraft connection only. No extra ports.